### ISSUE TITLE
Language folder should be created while generating language files

### ISSUE THREAD

**Issue by mahyard** [edx/i18n-tools#60]
I'm trying to generate language files for fa_IR which as you know there is not a **conf/locale/fa_IR** created by default.  
So I switched to edxapp, ran the following command from the installation directory of my xblock : `i18n_tool generate --strict` and then received this exception:  

> Exception: I18N: Cannot generate because file not found: /home/username/edx-sga/conf/locale/fa_IR/LC_MESSAGES/djangojs-partial.po  
 [Complete returned message](https://pastebin.com/raw/ewFUH36a)  

I think it would be more usable if the command create the appropriate folders automatically instead of ignoring those languages or raising error messagess.  

Note: As I'm trying to use i18n_tools to translate an xblock I can't fetch files from transifex.

**Comment by andy-armstrong** [comment]
Have you seen this wiki page? It might help:

https://github.com/edx/edx-platform/wiki/Internationalization-and-localization

**Comment by mahyard** [comment]
Yes I do, 
But it's useless if you don't want to download language files from transifex or as my case you can not do because they are not there.

**Comment by mahyard** [comment]
Hi @andy-armstrong , I have an idea,
is this possible to manually clone en/ and rename it to the new language for example fa_IR and start to translate strings? Most of our users don't make any changes in the source code of the xblock so they can easily do this to use it in their own language and get happy. Do you agree?
